package de.subcentral.core;

public interface PropNames
{
	public static final String	ALIAS_NAMES				= "aliasNames";
	public static final String	ATTRIBUTES				= "attributes";
	public static final String	BASIS					= "basis";
	public static final String	CONTENT_RATING			= "contentRating";
	public static final String	CONTRIBUTIONS			= "contributions";
	public static final String	COUNTRIES				= "countries";
	public static final String	DATE					= "date";
	public static final String	DESCRIPTION				= "description";
	public static final String	EPISODES				= "episodes";
	public static final String	FILE_COUNT				= "fileCount";
	public static final String	FINALE_DATE				= "finaleDate";
	public static final String	FURTHER_INFO_LINKS		= "furtherInfo";
	public static final String	GENRES					= "genres";
	public static final String	GROUP					= "group";
	public static final String	IDS						= "ids";
	public static final String	IMAGES					= "images";
	public static final String	LANGUAGE				= "language";
	public static final String	LANGUAGES				= "languages";
	public static final String	MATCHING_RELEASES		= "matchingReleases";
	public static final String	MEDIA					= "media";
	public static final String	MEDIA_CONTENT_TYPE		= "mediaContentType";
	public static final String	MEDIA_TYPE				= "mediaType";
	public static final String	NAME					= "name";
	public static final String	NETWORKS				= "networks";
	public static final String	NFO						= "nfo";
	public static final String	NFO_LINK				= "nfoUrl";
	public static final String	NUKES					= "nukes";
	public static final String	NUMBER					= "number";
	public static final String	NUMBER_IN_SEASON		= "numberInSeason";
	public static final String	NUMBER_IN_SERIES		= "numberInSeries";
	public static final String	PRODUCTION_TYPE			= "productionType";
	public static final String	RATINGS					= "ratings";
	public static final String	REGULAR_RUNNING_TIME	= "regularRunningTime";
	public static final String	RUNNING_TIME			= "runningTime";
	public static final String	SEASON					= "season";
	public static final String	SEASONS					= "seasons";
	public static final String	CATEGORY				= "category";
	public static final String	SERIES					= "series";
	public static final String	SIZE					= "size";
	public static final String	SOURCE					= "source";
	public static final String	SPECIAL					= "special";
	public static final String	STATE					= "state";
	public static final String	SUBTITLES				= "subtitles";
	public static final String	TAGS					= "tags";
	public static final String	TITLE					= "title";
	public static final String	TYPE					= "type";
	public static final String	UNNUKES					= "unnukes";
	public static final String	VERSION					= "version";
}
